project:
  type: website
  output-dir: docs

website:
  title: "Hambee Makinoda"
  favicon: icon.jpg
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
      - href: project.qmd
        text: Project
      - href: gallery.qmd
        text: Gallery
      - href: Education.qmd
        text: Classes
      - href: resume.pdf
        text: Resume
        target: _blank
      - icon: github
        href: //github.com/Hambanana0923
        target: _blank
  page-footer:
    left: Copyright 2026, Hambee Makinoda
    right: This website is built with [{{< fa brands github title="GitHub octocat logo" >}}](https://github.com/Hambanana0923/Hambanana0923.github.io){target=_blank}, [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank} and [Quarto](https://quarto.org/){target=_blank}
      

format:
  html:
    theme:
      - lux
      - brand
    css: styles.css
    toc: true
    page-layout: full

editor: visual

